// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzeuwomrnvrfsfnotxzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6ZXV3b21ybnZyZnNmbm90eHpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE0Mzk0ODUsImV4cCI6MjA4NzAxNTQ4NX0.ezu4LDwq7AzBbCsIk4t4ES8ASuo7UlK80hVNvX2MA8o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});